--- # swagger 설정
spring:
  mvc:
    pathmatch:
      matching-strategy:
        ant_path_matcher

--- # h2데이터베이스 설정
spring:
  # H2 Setting Info
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/local
    username: sa
    password:

--- # jpa
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
--- # 로그에서 sql 보기
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true # sql query formatting
        show_sql: true # sql 쿼리를 보여줍니다.
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace  # query의 ?에 어떤 값이 들어가는지 추적할 수 있는 설정입니다. TRACE Log에 값을 보여줍니다.

--- # 검증
#spring:
#  jpa:
#    properties:
#      javax:
#        persistence:
#          validation:
#            mode: none

