--- # swagger 설정
spring:
  mvc:
    pathmatch:
      matching-strategy:
        ant_path_matcher

--- # h2데이터베이스 설정
spring:
  # H2 Setting Info
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/local
    username: sa
    password:

--- # jpa
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
